### ISSUE TITLE
404 while running padpo

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/padpo#67]
Tried padpo v0.11 today on my laptop, got:

```
$ padpo -i  *.po
<frozen importlib._bootstrap>:1049: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:673: ImportWarning: VendorImporter.exec_module() not found; falling back to load_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:673: ImportWarning: _SixMetaPathImporter.exec_module() not found; falling back to load_module()
/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/pkg_resources/_vendor/pyparsing.py:87: DeprecationWarning: module 'sre_constants' is deprecated
  import sre_constants
<frozen importlib._bootstrap>:1049: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
Traceback (most recent call last):
  File "/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/pygrammalecte/pygrammalecte.py", line 108, in grammalecte_file
    result = _run_grammalecte(filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/pygrammalecte/pygrammalecte.py", line 139, in _run_grammalecte
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'grammalecte-cli.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mdk/clones/python/python-docs-fr/.venv/bin/padpo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/padpo/padpo.py", line 131, in main
    errors, warnings = check_paths(path, pull_request_info=pull_request_info)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/padpo/padpo.py", line 54, in check_paths
    errors, warnings = check_path(path, pull_request_info)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/padpo/padpo.py", line 46, in check_path
    return check_file(path, pull_request_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/padpo/padpo.py", line 23, in check_file
    checker.check_file(pofile)
  File "/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/padpo/checkers/grammalecte.py", line 40, in check_file
    self.manage_warnings(warnings, pofile)
  File "/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/padpo/checkers/grammalecte.py", line 48, in manage_warnings
    for warning in warnings:
  File "/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/pygrammalecte/pygrammalecte.py", line 97, in grammalecte_text
    yield from grammalecte_file(tmpfile)
  File "/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/pygrammalecte/pygrammalecte.py", line 112, in grammalecte_file
    _install_grammalecte()
  File "/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/pygrammalecte/pygrammalecte.py", line 163, in _install_grammalecte
    download_request.raise_for_status()
  File "/home/mdk/clones/python/python-docs-fr/.venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://grammalecte.net/grammalecte/zip/Grammalecte-fr-v1.12.0.zip

```

**Comment by vpoulailleau** [comment]
https://github.com/vpoulailleau/pygrammalecte/issues/9

**Comment by vpoulailleau** [comment]
Corrigé dans padpo v0.12.0
